= Bogo-logic
:Author: Bogoengine Team
:Email: <cmpitg@gmail.com>
:toc: left
:toclevels: 4
:numbered:
:icons: font
:source-highlighter: pygments
:pygments-css: class
:imagesdirs: assets/images

== Quy ước

Để nhất quán trong việc xử lý tiếng Việt, chúng ta thống nhất ý nghĩa của các
thuật ngữ sau trong Bogo-logic:

* _Dấu thanh_ là các dấu thay đổi thanh điệu của nguyên âm.  Tiếng Việt có 6
  loại dấu thanh:

** Thanh ngang (không dấu)
** Thanh huyền (+grave+)
** Thanh sắc (+acute+)
** Thanh hỏi (+hook+)
** Thanh ngã (+tilde+)
** Thanh nặng (+dot+)

.code::tone-defs
[source,lua,linenums]
----
local TONE_GRAVE,
      TONE_ACUTE,
      TONE_HOOK,
      TONE_TILDE,
      TONE_DOT,
      TONE_NONE = 1, 2, 3, 4, 5, 6
----

* _Dấu chữ cái_ là các dấu để tạo chữ cái mới từ chữ cái sẵn có:

** Dấu mũ (+hat+, như trong chữ cái +â+)
** Dấu móc (+horn+, như trong chữ cái +ơ+)
** Dấu trăng (+breve+, như trong chữ cái +ă+)
** Dấu ngang (+dash+, như trong chữ cái +đ+)

.code::mark-defs
[source,lua,linenums]
----
local MARK_BREVE,
      MARK_HAT,
      MARK_HORN,
      MARK_DASH,
      MARK_NONE = 1, 2, 3, 4, 5
----

* _Nguyên âm_ (+vowel+) là một âm thanh trong ngôn ngữ nói, được phát âm với
  thanh quản mở.  Ví dụ: _a_, _e_, _u_, _ư_, _uyê_, ...
+
_Phụ âm_ (+consonant+) là một âm thanh trong ngôn ngữ nói, được phát âm với
thanh quản đóng. Ví dụ: _b_, _c_, _ph_, _tr_, ...

WARNING: Khi ký âm (chuyển từ âm thanh sang chữ viết), nguyên âm hay phụ âm có
thể được tạo thành từ một hoặc nhiều chữ cái.  Khái niệm nguyên âm, phụ âm
thường bị hiểu sai là một chữ cái đơn lẻ.

NOTE: Khi nói về nguyên âm hoặc phụ âm chỉ được cấu tạo bởi một chữ cái, chúng
tôi sẽ dùng _chữ cái nguyên âm_ và _chữ cái phụ âm_ tương ứng.

* _Âm tiết_ (+syllable+) là đơn vị cấu tạo từ cơ bản.  Ví dụ:

** Từ _nhà_ có một âm tiết: _nhà_.
** Từ _la-tinh_ có 2 âm tiết: _la_ và _tinh_.
** Từ _hợp tác xã_ có 3 âm tiết: _hợp_, _tác_, và _xã_.

== Xử lý tiếng Việt

Như mọi bộ gõ khác, phần quan trọng nhất của Bogo-logic là xử lý tiếng Việt.
Công việc này được chia thành 2 thao tác lớn:

* Thêm _dấu chữ cái_
* Thêm _dấu thanh_

Để thêm dấu thanh, trước hết chúng ta sẽ định nghĩa một bảng tra cứu tuần hoàn
tất cả các chữ cái nguyên âm trong tiếng Việt với tất cả các tổ hợp dấu thanh có
thể.

.code::vowel-chars-defs
[source,lua,linenums]
----
local VOWEL_CHARS = {
    "à", "á", "ả", "ã", "ạ", "a", "ằ", "ắ", "ẳ", "ẵ", "ặ", "ă",
    "ầ", "ấ", "ẩ", "ẫ", "ậ", "â", "è", "é", "ẻ", "ẽ", "ẹ", "e",
    "ề", "ế", "ể", "ễ", "ệ", "ê", "ì", "í", "ỉ", "ĩ", "ị", "i",
    "ò", "ó", "ỏ", "õ", "ọ", "o", "ồ", "ố", "ổ", "ỗ", "ộ", "ô",
    "ờ", "ớ", "ở", "ỡ", "ợ", "ơ", "ù", "ú", "ủ", "ũ", "ụ", "u",
    "ừ", "ứ", "ử", "ữ", "ự", "ư", "ỳ", "ý", "ỷ", "ỹ", "ỵ", "y"
}
----

Để ý kỹ có thể thấy ngay các chữ cái nguyên âm trong bảng được sắp xếp theo trật
tự huyền, sắc, hỏi, ngã, nặng, ngang, đúng với trật tự chúng ta đã định nghĩa các
mã dấu thanh ở trên. Nhờ vậy, chúng ta có thể định nghĩa thuật toán thêm dấu thanh
đơn giản là tìm vị trí nhóm nguyên âm tương ứng với nguyên âm cần thêm dấu trong
bảng và sử dụng mã dấu thanh cần thêm làm tọa độ tương đối so với nhóm.

.code::add-tone-char
[source,lua,linenums]
----
-- include::vowel-chars-defs

function add_tone_char (char, tone)
    for i, v in pairs(VOWEL_CHARS) do
        if char == v then
            return VOWEL_CHARS[math.floor((i - 1) / 6) * 6 + tone]
        end
    end

    return char
end

describe("add_tone_char", function ()
    it("adds a tone to a char", function ()
        assert.are.equal(add_tone_char ("a", TONE_ACUTE), "á")
        assert.are.equal(add_tone_char ("ỷ", TONE_HOOK), "ỷ")
        assert.are.equal(add_tone_char ("ụ", TONE_NONE), "u")
    end)
end)
----


Công việc đầu tiên cần làm là định nghĩa cấu trúc dữ liệu tốt, thuận tiện cho
việc xử lý tiếng Việt.

=== Cấu trúc dữ liệu cho _âm tiết_

.file::/tmp/tmp.lua
[source,lua,linenums]
----
----
